plugins/redmine_contacts/config/routes.rb
#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
    end
  end
  
  resources :projects do 
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do 
        get :contacts_notes
      end
    end

  end
  
  resources :deals do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
    end
  end

  resources :projects do 
    resources :deals, :only => [:new, :create, :index]
  end

  resources :projects do 
    resources :contacts_queries, :only => [:new, :create]
  end  

  resources :contacts_queries, :except => [:show]

  resources :deal_statuses, :except => :show do
    collection do
      put :assing_to_project
    end
  end

  resources :notes

  match 'projects/:project_id/contacts/:contact_id/new_task' => 'contacts_tasks#new', :via => :post

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index'

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new'
 
  match 'projects/:project_id/sales_funnel'  => 'sales_funnel#index'
  match 'sales_funnel/:action' => 'sales_funnel#index'



  # match 'notes/:note_id' => 'notes#show', :via => :get, :as => "note"
  # match 'notes/show/:note_id' => 'notes#show', :via => :get
  # match 'notes/:note_id/edit' => 'notes#edit', :via => :get
  # match 'notes/:note_id/update' => 'notes#update', :via => :put
  # match 'notes/add_note' => 'notes#add_note'
  # match 'notes/destroy' => 'notes#destroy'
  
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'
  
  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates'
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_projects/:action' => 'contacts_projects'
  match 'contacts_tags/:action' => 'contacts_tags'
  match 'contacts_tasks/:action' => 'contacts_tasks'
  match 'contacts_vcf/:action' => 'contacts_vcf'
  match 'deal_categories/:action' => 'deal_categories'
  match 'deal_contacts/:action' => 'deal_contacts'
  match 'deals_tasks/:action' => 'deals_tasks'
  match 'contacts_settings/:action' => 'contacts_settings'
  match 'contacts_mailer/:action' => 'contacts_mailer'
  match 'deals_tasks/:action' => 'deals_tasks'
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

    

plugins/redmine_contacts/app/views/projects/_contacts.html.erb
<% if ContactsSetting[:contacts_show_on_projects_show, @project.id].to_i > 0 && User.current.allowed_to?(:view_contacts, @project) %>

<% contacts = Contact.visible.by_project(@project).limit(50).order("#{Contact.table_name}.created_on DESC") %>

<% if contacts.length > 0 %>
  <div class="box" id="duplicates">  
  <h3 class="icon icon-vcard"><%= l(:label_contact_plural) %></h3>

  <% if contacts.select{|c| !c.is_company}.any? %>
  <div id="duplicates">                                  
    <% contacts.select{|c| !c.is_company}.each do |contact| %>   
      <div class="avatar tooltip" style="display: inline;">
        <%= link_to avatar_to(contact, :size => "64"),  contact_path(contact), :id => "avatar" %>
        <span class="tip contact"><%= render_contact_tooltip(contact, :icon => true) %></span>
      </div>
  	<% end %>    
  </div>  
  <% end %>
  
  <% if contacts.select{|c| c.is_company}.any? %>
  <div id="duplicates">                                  
    <% contacts.select{|c| c.is_company}.each do |contact| %>   
      <div class="avatar tooltip" style="display: inline;">
      <%= link_to avatar_to(contact, :size => "64"),  contact_path(contact), :id => "avatar" %>
      <span class="tip contact"><%= render_contact_tooltip(contact, :icon => true) %></span>
      </div>
  	<% end %>    
  </div>  
  <% end %>



	<p class="small"><%= link_to l(:label_contact_view_all), 
						 :controller => 'contacts',
						 :action => 'index',
						 :project_id => project.id %></p>
	</div>					 
<% end %>

<% content_for(:header_tags) do %>
	<%= javascript_include_tag :contacts, :plugin => 'redmine_contacts'  %>
  	<%= stylesheet_link_tag :contacts, :plugin => 'redmine_contacts' %> 
<% end %>

<% end %>

plugins/redmine_contacts/app/views/projects/_contacts_settings.html.erb
<%= form_tag({:controller => "contacts_settings", :action => "save", :project_id => @project, :tab => 'contacts'}, :method => :post, :class => "tabular") do %> 
  <div class="tabular box">

    <p>  
      <label><%= l(:label_show_on_projects_show) %></label>
      <%= hidden_field_tag('contacts_settings[contacts_show_on_projects_show]', 0)  %>
      <%= check_box_tag 'contacts_settings[contacts_show_on_projects_show]', 1, ContactsSetting[:contacts_show_on_projects_show, @project.id].to_i > 0 %>
    </p>

    <%= call_hook(:view_contacts_project_settings_bottom, :project => @project) %>
  
  </div>

  <%= submit_tag l(:button_save) %>
<% end %>

plugins/redmine_contacts/app/views/projects/_deal_statuses.html.erb
<h3><%= l(:label_deal_status_plural) %></h3>

<% if DealStatus.all.any? %>  
	<%= form_tag({:controller => "deal_statuses", :action => "assing_to_project", :project_id => @project, :tab => 'deals'}, :method => :put, :class => "tabular") do %> 
	<table class="list">
		<thead><tr>
		<th><%= l(:field_name) %></th>  
		<th><%=l(:field_is_default)%></th>
	  	<th><%=l(:label_crm_deal_status_type)%></th>
	    <th style="width:15%;"><%= l(:field_active) %></th>
		</tr></thead>
		<tbody> 
		<% DealStatus.all( :order => "status_type, position").each do |status| %>  
	  
			<tr class="<%= cycle 'odd', 'even' %>">
			<td><span class="color" style="border: 1px solid #D7D7D7;background-color: <%= status.color_name %>;">&nbsp;&nbsp;&nbsp;&nbsp;</span> <%= h(status.name) %></td>
		    <td align="center" style="width:15%;"><%= checked_image status.is_default? %></td>
		  	<td align="center" style="width:15%;"><%= status.status_type_name %></td>
			<td align="center" style="width:15%;">
		      <%= check_box_tag "deal_statuses[]", status.id , @project.deal_statuses.include?(status) %>
		    </td>
			</tr>   
		<% end %>
	    </tbody>
	</table>  
	<%= submit_tag l(:button_save) %>
	<% end %>
<% end %>  

plugins/redmine_contacts/app/views/projects/_deals_settings.html.erb
<h3><%= l(:label_deal_category_plural) %></h3> 

<% if @project.deal_categories.any? %>
<table class="list">
	<thead><tr>
	<th><%= l(:field_name) %></th>
	<th></th>
	</tr></thead>
	<tbody>
<% for category in @project.deal_categories %>
	<% unless category.new_record? %>
	<tr class="<%= cycle 'odd', 'even' %>">
	<td><%= link_to_if_authorized h(category.name), { :controller => 'deal_categories', :action => 'edit', :id => category } %></td>
    <td class="buttons">
    	<%= link_to_if_authorized l(:button_delete), {:controller => 'deal_categories', :action => 'destroy', :id => category}, :method => :post, :confirm => l(:text_are_you_sure), :class => 'icon icon-del' %>
    </td>
	</tr>
	<% end %>
<% end %>
    </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

<p><%= link_to_if_authorized l(:label_deal_category_new), :controller => 'deal_categories', :action => 'new', :project_id => @project %></p>

<%= render :partial => "projects/deal_statuses" %>